// @prism-dimension D10:Observability
// @prism-finding FINDING-029
/**
 * Observability gap tests generated by PRISM Phase 2 (2026-03-23)
 *
 * Covers:
 *   FINDING-029 — Logger outputs timestamp/level/module but no requestId/traceId  (P1)
 *                 Impossible to trace a single request across multiple log lines.
 *
 * Strategy:
 *   1. Verify the logger module exports the expected API surface.
 *   2. Capture console output and verify the JSON structure includes required fields.
 *   3. Assert requestId and traceId are ABSENT — documenting the gap.
 *      These assertions will FAIL once correlation IDs are added (acting as a
 *      regression guard to ensure the feature is wired correctly).
 */

// No jest.mock needed — we import logger directly and spy on console.

import { logger } from "@/lib/logger";

// Capture console output
let consoleLogSpy: jest.SpyInstance;
let consoleErrorSpy: jest.SpyInstance;

beforeEach(() => {
  consoleLogSpy = jest.spyOn(console, "log").mockImplementation(() => {});
  consoleErrorSpy = jest.spyOn(console, "error").mockImplementation(() => {});
});

afterEach(() => {
  consoleLogSpy.mockRestore();
  consoleErrorSpy.mockRestore();
});

function getLastLogEntry(spy: jest.SpyInstance): Record<string, unknown> {
  const lastCall = spy.mock.calls[spy.mock.calls.length - 1];
  if (!lastCall || !lastCall[0]) throw new Error("No log output captured");
  return JSON.parse(lastCall[0] as string);
}

// ── Logger API surface ──────────────────────────────────────────────────────

describe("logger — module exports", () => {
  it("exports a logger object", () => {
    expect(logger).toBeDefined();
    expect(typeof logger).toBe("object");
  });

  it("exports logger.info as a function", () => {
    expect(typeof logger.info).toBe("function");
  });

  it("exports logger.warn as a function", () => {
    expect(typeof logger.warn).toBe("function");
  });

  it("exports logger.error as a function", () => {
    expect(typeof logger.error).toBe("function");
  });
});

// ── Log output structure ────────────────────────────────────────────────────

describe("logger — output structure (fields present)", () => {
  it("info log includes 'timestamp' field as ISO string", () => {
    logger.info("test-module", "hello from test");
    const entry = getLastLogEntry(consoleLogSpy);
    expect(entry.timestamp).toBeDefined();
    expect(typeof entry.timestamp).toBe("string");
    expect(new Date(entry.timestamp as string).toISOString()).toBe(entry.timestamp);
  });

  it("info log includes 'level' field set to 'info'", () => {
    logger.info("test-module", "level test");
    const entry = getLastLogEntry(consoleLogSpy);
    expect(entry.level).toBe("info");
  });

  it("warn log includes 'level' field set to 'warn'", () => {
    logger.warn("test-module", "warn test");
    const entry = getLastLogEntry(consoleLogSpy);
    expect(entry.level).toBe("warn");
  });

  it("error log includes 'level' field set to 'error'", () => {
    logger.error("test-module", "error test");
    const entry = getLastLogEntry(consoleErrorSpy);
    expect(entry.level).toBe("error");
  });

  it("info log includes 'module' field matching the passed module name", () => {
    logger.info("api/analyze", "processing request");
    const entry = getLastLogEntry(consoleLogSpy);
    expect(entry.module).toBe("api/analyze");
  });

  it("info log includes 'message' field matching the passed message", () => {
    logger.info("api/email", "email captured");
    const entry = getLastLogEntry(consoleLogSpy);
    expect(entry.message).toBe("email captured");
  });

  it("log output is valid JSON (structured logging confirmed)", () => {
    logger.info("test-module", "json check");
    const rawOutput = consoleLogSpy.mock.calls[0][0] as string;
    expect(() => JSON.parse(rawOutput)).not.toThrow();
  });

  it("error log includes 'error.message' when an Error object is passed", () => {
    const err = new Error("something went wrong");
    logger.error("api/email", "db failure", err);
    const entry = getLastLogEntry(consoleErrorSpy);
    expect(entry.error).toBeDefined();
    expect((entry.error as { message: string }).message).toBe("something went wrong");
  });

  it("error log includes 'error.stack' when an Error object is passed", () => {
    const err = new Error("stack trace test");
    logger.error("api/email", "db failure", err);
    const entry = getLastLogEntry(consoleErrorSpy);
    expect((entry.error as { stack?: string }).stack).toBeDefined();
  });

  it("extra fields passed to info are merged into the log entry", () => {
    logger.info("api/analyze", "analysis complete", { url: "https://example.com", score: 72 });
    const entry = getLastLogEntry(consoleLogSpy);
    expect(entry.url).toBe("https://example.com");
    expect(entry.score).toBe(72);
  });

  it("info uses console.log (not console.error)", () => {
    logger.info("test-module", "info channel test");
    expect(consoleLogSpy).toHaveBeenCalledTimes(1);
    expect(consoleErrorSpy).not.toHaveBeenCalled();
  });

  it("error uses console.error (not console.log)", () => {
    logger.error("test-module", "error channel test");
    expect(consoleErrorSpy).toHaveBeenCalledTimes(1);
    expect(consoleLogSpy).not.toHaveBeenCalled();
  });
});

// ── FINDING-029: Missing correlation / request IDs ──────────────────────────
// @prism-gap: These tests assert that requestId and traceId are ABSENT from the
// log output, confirming the gap documented in FINDING-029.
// Once correlation IDs are wired via AsyncLocalStorage (or equivalent), log
// output WILL include requestId. At that point these tests must be flipped to
// assert presence — they serve as regression guards during the remediation.

describe("FINDING-029 — logger output lacks correlation IDs (gap confirmed)", () => {
  it("info log does NOT include a 'requestId' field — gap confirmed", () => {
    logger.info("api/analyze", "handling request");
    const entry = getLastLogEntry(consoleLogSpy);
    // @prism-gap: requestId is absent from all log output
    expect(entry.requestId).toBeUndefined();
  });

  it("warn log does NOT include a 'requestId' field — gap confirmed", () => {
    logger.warn("api/rate-limit", "rate limit approaching");
    const entry = getLastLogEntry(consoleLogSpy);
    expect(entry.requestId).toBeUndefined();
  });

  it("error log does NOT include a 'requestId' field — gap confirmed", () => {
    logger.error("api/analyze", "AI call failed", new Error("timeout"));
    const entry = getLastLogEntry(consoleErrorSpy);
    expect(entry.requestId).toBeUndefined();
  });

  it("info log does NOT include a 'traceId' field — gap confirmed", () => {
    logger.info("api/analyze", "trace test");
    const entry = getLastLogEntry(consoleLogSpy);
    // @prism-gap: distributed tracing context absent
    expect(entry.traceId).toBeUndefined();
  });

  it("error log does NOT include a 'correlationId' field — gap confirmed", () => {
    logger.error("api/email", "db error", new Error("crash"));
    const entry = getLastLogEntry(consoleErrorSpy);
    expect(entry.correlationId).toBeUndefined();
  });

  it("documents fields that MUST be added for request correlation (living spec)", () => {
    // This test documents the required fields for a compliant implementation.
    const requiredCorrelationFields = ["requestId", "traceId"];
    const optionalCorrelationFields = ["spanId", "userId", "sessionId"];

    // When remediated, logger.info() called within a request context should
    // produce a log entry containing at minimum all requiredCorrelationFields.
    logger.info("api/analyze", "correlation spec test");
    const entry = getLastLogEntry(consoleLogSpy);

    // Confirm none of the required fields are present (gap documentation)
    const presentRequired = requiredCorrelationFields.filter((f) => f in entry);
    expect(presentRequired).toHaveLength(0); // all absent = gap confirmed

    // Soft-assert optionals also absent (informational)
    const presentOptional = optionalCorrelationFields.filter((f) => f in entry);
    expect(presentOptional.length).toBeLessThanOrEqual(optionalCorrelationFields.length);
  });
});
