// @prism-dimension D4:Security
// @prism-finding FINDING-001 FINDING-002 FINDING-005 FINDING-006
/**
 * Security regression tests generated by PRISM Phase 2 (2026-03-23)
 *
 * Covers:
 *   FINDING-001 — No rate limiting on POST /api/auth/request-otp  (P0)
 *   FINDING-002 — No rate limiting / brute-force protection on POST /api/auth/verify-otp  (P0)
 *   FINDING-005 — /api/email accepts unauthenticated requests  (P1)
 *   FINDING-006 — No rate limiting on POST /api/email  (P1)
 *
 * These tests CONFIRM the vulnerabilities exist (i.e. the "bad" behaviour passes).
 * They are intentionally written to FAIL once the issues are fixed — acting as
 * regression guards that turn green only when the fix is in place.
 * Tests marked @prism-gap document behaviours that cannot be asserted purely with
 * unit tests (e.g. real IP-based in-memory counters) — they confirm the gap instead.
 */

// ── mocks ──────────────────────────────────────────────────────────────────

const mockOtpToken = {
  updateMany: jest.fn(),
  create: jest.fn(),
  findFirst: jest.fn(),
  update: jest.fn(),
};
const mockUser = { upsert: jest.fn() };
const mockEmailCapture = { create: jest.fn() };

jest.mock("@/lib/db", () => ({
  prisma: {
    get otpToken() { return mockOtpToken; },
    get user() { return mockUser; },
    get emailCapture() { return mockEmailCapture; },
    $transaction: jest.fn(async (fn: (tx: unknown) => Promise<unknown>) =>
      fn({ otpToken: mockOtpToken, user: mockUser })
    ),
  },
}));
jest.mock("@/lib/email", () => ({ sendOtpEmail: jest.fn() }));
jest.mock("@/lib/session", () => ({
  createSessionToken: jest.fn(() => Promise.resolve("jwt.session.token")),
  sessionCookieHeader: jest.fn(
    () => "auth_session=jwt.session.token; HttpOnly; Path=/; SameSite=Lax; Max-Age=604800"
  ),
  getSessionFromRequest: jest.fn(() => Promise.resolve(null)),
}));

import { POST as requestOtp } from "@/app/api/auth/request-otp/route";
import { POST as verifyOtp } from "@/app/api/auth/verify-otp/route";
import { POST as emailCapture } from "@/app/api/email/route";
import { NextRequest } from "next/server";
import { sendOtpEmail } from "@/lib/email";

const mockSendEmail = sendOtpEmail as jest.MockedFunction<typeof sendOtpEmail>;

function makeReq(path: string, body: unknown) {
  return new NextRequest(`http://localhost${path}`, {
    method: "POST",
    body: JSON.stringify(body),
    headers: { "Content-Type": "application/json" },
  });
}

beforeEach(() => {
  jest.clearAllMocks();
  mockOtpToken.updateMany.mockResolvedValue({ count: 0 });
  mockOtpToken.create.mockResolvedValue({ id: "otp1" });
  mockOtpToken.findFirst.mockResolvedValue(null); // default: OTP not found (invalid)
  mockOtpToken.update.mockResolvedValue({ id: "otp1" });
  mockUser.upsert.mockResolvedValue({ id: "user1", email: "victim@example.com" });
  mockEmailCapture.create.mockResolvedValue({ id: "cap1" });
  mockSendEmail.mockResolvedValue(undefined);
});

// ── FINDING-001: No rate limiting on OTP request ────────────────────────────
// @prism-gap: rate-limit enforcement requires a real counter store (Redis/memory).
// These tests confirm the vulnerability: the handler returns 200 on every call
// regardless of call frequency. Once a rate-limit is added the handler should
// return 429 on the Nth call, which will cause these tests to fail.

describe("FINDING-001 — OTP request endpoint has no rate limiting", () => {
  it("returns 200 on first OTP request", async () => {
    const res = await requestOtp(makeReq("/api/auth/request-otp", { email: "victim@example.com" }));
    expect(res.status).toBe(200);
  });

  it("returns 200 on second rapid OTP request for same email (no throttle)", async () => {
    await requestOtp(makeReq("/api/auth/request-otp", { email: "victim@example.com" }));
    const res = await requestOtp(makeReq("/api/auth/request-otp", { email: "victim@example.com" }));
    expect(res.status).toBe(200);
  });

  it("returns 200 on ten rapid OTP requests — confirms no 429 is ever returned", async () => {
    const results: number[] = [];
    for (let i = 0; i < 10; i++) {
      const res = await requestOtp(
        makeReq("/api/auth/request-otp", { email: "victim@example.com" })
      );
      results.push(res.status);
    }
    // All calls succeed — no rate limit is applied (vulnerability confirmed)
    expect(results.every((s) => s === 200)).toBe(true);
    expect(results).not.toContain(429);
  });

  it("sends an email on every call — email quota exhaustion possible", async () => {
    for (let i = 0; i < 5; i++) {
      await requestOtp(makeReq("/api/auth/request-otp", { email: "victim@example.com" }));
    }
    expect(mockSendEmail).toHaveBeenCalledTimes(5);
  });

  it("creates a new OTP DB record on every call — no dedup guard", async () => {
    for (let i = 0; i < 5; i++) {
      await requestOtp(makeReq("/api/auth/request-otp", { email: "victim@example.com" }));
    }
    expect(mockOtpToken.create).toHaveBeenCalledTimes(5);
  });
});

// ── FINDING-002: No rate limiting on OTP verify ─────────────────────────────
// @prism-gap: same as FINDING-001. A proper brute-force guard would return 429
// or 401 with a lockout flag after N failed attempts. This confirms the gap:
// every attempt resolves independently with no attempt counter.

describe("FINDING-002 — OTP verify endpoint has no brute-force lockout", () => {
  it("returns 401 (not locked out) on a single bad OTP attempt", async () => {
    mockOtpToken.findFirst.mockResolvedValue(null);
    const res = await verifyOtp(
      makeReq("/api/auth/verify-otp", { email: "victim@example.com", token: "000001" })
    );
    expect(res.status).toBe(401);
    const body = await res.json();
    expect(body.error).toMatch(/invalid|expired/i);
    // No lockout flag or retryAfter header present
    expect(body.lockedOut).toBeUndefined();
    expect(body.retryAfter).toBeUndefined();
  });

  it("returns 401 on every one of ten consecutive bad OTP attempts — no lockout", async () => {
    mockOtpToken.findFirst.mockResolvedValue(null);
    const statuses: number[] = [];
    for (let i = 0; i < 10; i++) {
      const token = String(100000 + i).padStart(6, "0");
      const res = await verifyOtp(
        makeReq("/api/auth/verify-otp", { email: "victim@example.com", token })
      );
      statuses.push(res.status);
    }
    // Attacker receives 401 every time — never locked out, never rate-limited
    expect(statuses).not.toContain(429);
    expect(statuses.every((s) => s === 401)).toBe(true);
  });

  it("allows correct OTP after many failed attempts — no lockout mechanism", async () => {
    mockOtpToken.findFirst.mockResolvedValue(null);
    // Simulate 9 failed attempts
    for (let i = 0; i < 9; i++) {
      await verifyOtp(
        makeReq("/api/auth/verify-otp", { email: "victim@example.com", token: "000000" })
      );
    }
    // 10th attempt uses correct OTP
    const correctOtp = { id: "otp1", email: "victim@example.com", token: "123456" };
    mockOtpToken.findFirst.mockResolvedValue(correctOtp);
    const res = await verifyOtp(
      makeReq("/api/auth/verify-otp", { email: "victim@example.com", token: "123456" })
    );
    // Should be 401/429 if locked out — currently returns 200 (no lockout = vulnerability confirmed)
    expect(res.status).toBe(200);
  });
});

// ── FINDING-005: /api/email — no authentication required ───────────────────

describe("FINDING-005 — /api/email accepts unauthenticated requests", () => {
  it("returns 200 with no auth header or session cookie", async () => {
    // Request has no Authorization header, no Cookie header — completely unauthenticated
    const req = new NextRequest("http://localhost/api/email", {
      method: "POST",
      body: JSON.stringify({ email: "attacker@evil.com", slug: "abc123" }),
      headers: { "Content-Type": "application/json" },
      // No Cookie or Authorization headers
    });
    const res = await emailCapture(req);
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body.ok).toBe(true);
  });

  it("stores email for any slug without verifying slug ownership", async () => {
    const req = makeReq("/api/email", {
      email: "attacker@evil.com",
      slug: "someones-private-slug-xyz",
    });
    const res = await emailCapture(req);
    expect(res.status).toBe(200);
    expect(mockEmailCapture.create).toHaveBeenCalledWith(
      expect.objectContaining({
        data: expect.objectContaining({
          email: "attacker@evil.com",
          slug: "someones-private-slug-xyz",
        }),
      })
    );
  });

  it("allows any email address to be associated with any slug", async () => {
    const victims = ["user1@corp.com", "user2@corp.com", "user3@corp.com"];
    for (const email of victims) {
      const res = await emailCapture(makeReq("/api/email", { email, slug: "public-slug" }));
      expect(res.status).toBe(200);
    }
    expect(mockEmailCapture.create).toHaveBeenCalledTimes(3);
  });
});

// ── FINDING-006: /api/email — no rate limiting ──────────────────────────────
// @prism-gap: same caveat as FINDING-001/002. Tests confirm handler returns
// 200 on every call with no 429.

describe("FINDING-006 — /api/email has no rate limiting", () => {
  it("returns 200 on repeated identical submissions — no dedup or rate limit", async () => {
    const statuses: number[] = [];
    for (let i = 0; i < 10; i++) {
      const res = await emailCapture(
        makeReq("/api/email", { email: "bulk@attacker.com", slug: "target-slug" })
      );
      statuses.push(res.status);
    }
    expect(statuses.every((s) => s === 200)).toBe(true);
    expect(statuses).not.toContain(429);
  });

  it("creates a new DB row for every duplicate submission — no dedup logic", async () => {
    for (let i = 0; i < 5; i++) {
      await emailCapture(makeReq("/api/email", { email: "dup@example.com", slug: "slug-abc" }));
    }
    // Each call inserts a new record — no idempotency check
    expect(mockEmailCapture.create).toHaveBeenCalledTimes(5);
  });

  it("accepts different email addresses rapidly — bulk harvesting possible", async () => {
    const statuses: number[] = [];
    for (let i = 0; i < 20; i++) {
      const res = await emailCapture(
        makeReq("/api/email", { email: `target${i}@corp.com`, slug: "harvested-slug" })
      );
      statuses.push(res.status);
    }
    expect(statuses).not.toContain(429);
    expect(mockEmailCapture.create).toHaveBeenCalledTimes(20);
  });
});
