// @prism-dimension D9:Compliance
// @prism-finding FINDING-022 FINDING-023
/**
 * Compliance & Privacy gap tests generated by PRISM Phase 2 (2026-03-23)
 *
 * Covers:
 *   FINDING-022 — No data retention policies; records accumulate indefinitely  (P1)
 *   FINDING-023 — No right-to-erasure endpoint; GDPR Article 17 non-compliance  (P1)
 *
 * Strategy: these are structural/architectural gaps not expressible as HTTP round-trips.
 * Tests confirm the gap by:
 *   1. Verifying no DELETE /api/auth/account route module exists in the codebase.
 *   2. Verifying no scheduled cleanup / TTL mechanism exists.
 *   3. Verifying the Prisma schema models known to accumulate PII exist but have no
 *      TTL or scheduled purge wiring.
 */

// ── mocks ──────────────────────────────────────────────────────────────────

jest.mock("@/lib/db", () => ({
  prisma: {
    user: { delete: jest.fn(), findUnique: jest.fn() },
    analysisResult: { deleteMany: jest.fn(), count: jest.fn() },
    emailCapture: { deleteMany: jest.fn(), count: jest.fn() },
    otpToken: { deleteMany: jest.fn(), count: jest.fn() },
    postHogConfig: { delete: jest.fn() },
  },
}));

import * as fs from "fs";
import * as path from "path";
import { prisma } from "@/lib/db";

const mockUserDelete = prisma.user.delete as jest.MockedFunction<typeof prisma.user.delete>;
const mockAnalysisDeleteMany = prisma.analysisResult.deleteMany as jest.MockedFunction<typeof prisma.analysisResult.deleteMany>;
const mockEmailCaptureDeleteMany = prisma.emailCapture.deleteMany as jest.MockedFunction<typeof prisma.emailCapture.deleteMany>;
const mockOtpDeleteMany = prisma.otpToken.deleteMany as jest.MockedFunction<typeof prisma.otpToken.deleteMany>;

const API_DIR = path.join(process.cwd(), "src", "app", "api");
const LIB_DIR = path.join(process.cwd(), "src", "lib");
const PRISMA_SCHEMA = path.join(process.cwd(), "prisma", "schema.prisma");

beforeEach(() => {
  jest.clearAllMocks();
});

// ── FINDING-023: No right-to-erasure endpoint ───────────────────────────────

describe("FINDING-023 — No DELETE /api/auth/account endpoint exists", () => {
  it("confirms no account-deletion route file exists in the API tree", () => {
    // GDPR Art. 17 requires a mechanism to delete all user data on request.
    // Check that no route.ts exists under /api/auth/account/
    const accountDir = path.join(API_DIR, "auth", "account");
    const routeFile = path.join(accountDir, "route.ts");
    const exists = fs.existsSync(routeFile);
    // @prism-gap: This should be FALSE (gap confirmed). When the feature is
    // implemented this test must be updated to assert exists === true AND
    // that DELETE method is exported.
    expect(exists).toBe(false);
  });

  it("confirms no delete-account or erasure script exists in src/lib/", () => {
    const libFiles = fs.readdirSync(LIB_DIR);
    const deletionRelated = libFiles.filter((f) =>
      /delete|erase|purge|gdpr|forget/i.test(f)
    );
    // @prism-gap: no erasure utility module found
    expect(deletionRelated).toHaveLength(0);
  });

  it("documents the data that MUST be deleted to satisfy right-to-erasure", () => {
    // This test documents the required scope for a compliant implementation.
    // All of these prisma operations would need to run as part of account deletion.
    const requiredOperations = [
      "user.delete — remove the User record",
      "analysisResult.deleteMany — purge all analyses by userId",
      "emailCapture.deleteMany — purge all email captures linked to user slugs",
      "otpToken.deleteMany — purge all OTP tokens for user email",
      "postHogConfig.delete — purge encrypted PostHog API key",
    ];
    // Snapshot acts as a living spec for the required endpoint
    expect(requiredOperations).toHaveLength(5);
    expect(requiredOperations[0]).toContain("user.delete");
    expect(requiredOperations[1]).toContain("analysisResult.deleteMany");
    expect(requiredOperations[2]).toContain("emailCapture.deleteMany");
  });

  it("mock-verifies a compliant erasure sequence touches all required tables", async () => {
    // Demonstrate what a compliant implementation would call on prisma.
    // This test will be refactored to import the real route once it exists.
    mockUserDelete.mockResolvedValue({ id: "u1", email: "gone@example.com" } as never);
    mockAnalysisDeleteMany.mockResolvedValue({ count: 3 } as never);
    mockEmailCaptureDeleteMany.mockResolvedValue({ count: 5 } as never);
    mockOtpDeleteMany.mockResolvedValue({ count: 2 } as never);

    // Simulate what a compliant DELETE /api/auth/account handler must call:
    const userId = "u1";
    const userEmail = "gone@example.com";

    await prisma.analysisResult.deleteMany({ where: { userId } } as never);
    await prisma.emailCapture.deleteMany({ where: {} } as never); // slug-based join needed
    await prisma.otpToken.deleteMany({ where: { email: userEmail } } as never);
    await prisma.user.delete({ where: { id: userId } } as never);

    expect(mockAnalysisDeleteMany).toHaveBeenCalledTimes(1);
    expect(mockEmailCaptureDeleteMany).toHaveBeenCalledTimes(1);
    expect(mockOtpDeleteMany).toHaveBeenCalledTimes(1);
    expect(mockUserDelete).toHaveBeenCalledTimes(1);
  });
});

// ── FINDING-022: No data retention policies ─────────────────────────────────

describe("FINDING-022 — No data retention or TTL mechanism exists", () => {
  it("confirms no cron or scheduled task file exists in the codebase", () => {
    const rootFiles = fs.readdirSync(process.cwd());
    const hasCronConfig = rootFiles.some((f) =>
      /cron|schedule|cleanup|retention/i.test(f)
    );
    // @prism-gap: no cron configuration found at repository root
    expect(hasCronConfig).toBe(false);
  });

  it("confirms OtpToken model has no expiresAt-based auto-purge wiring", () => {
    const schema = fs.readFileSync(PRISMA_SCHEMA, "utf-8");
    // SQLite has no native TTL. A cleanup job must explicitly delete expired tokens.
    // Confirm there is no deleteMany call targeting OtpToken by createdAt in lib/
    const libFiles = fs.readdirSync(LIB_DIR).map((f) => path.join(LIB_DIR, f));
    const hasOtpCleanup = libFiles.some((filePath) => {
      if (!filePath.endsWith(".ts")) return false;
      const content = fs.readFileSync(filePath, "utf-8");
      return /otpToken\.deleteMany/i.test(content);
    });
    // @prism-gap: no OTP cleanup found in lib modules
    expect(hasOtpCleanup).toBe(false);
    // Schema does have expiresAt field — but no cleanup job uses it
    expect(schema).toContain("expiresAt");
  });

  it("confirms AnalysisResult has no createdAt-based retention purge in lib/", () => {
    const libFiles = fs.readdirSync(LIB_DIR).map((f) => path.join(LIB_DIR, f));
    const hasRetentionPurge = libFiles.some((filePath) => {
      if (!filePath.endsWith(".ts")) return false;
      const content = fs.readFileSync(filePath, "utf-8");
      return /analysisResult\.deleteMany/i.test(content) && /createdAt/i.test(content);
    });
    // @prism-gap: no age-based purge of AnalysisResult records found
    expect(hasRetentionPurge).toBe(false);
  });

  it("confirms EmailCapture has no purge mechanism in lib/", () => {
    const libFiles = fs.readdirSync(LIB_DIR).map((f) => path.join(LIB_DIR, f));
    const hasEmailCapturePurge = libFiles.some((filePath) => {
      if (!filePath.endsWith(".ts")) return false;
      const content = fs.readFileSync(filePath, "utf-8");
      return /emailCapture\.deleteMany/i.test(content);
    });
    // @prism-gap: EmailCapture (PII) accumulates indefinitely
    expect(hasEmailCapturePurge).toBe(false);
  });

  it("documents the records that accumulate indefinitely", () => {
    // Living documentation of the retention gap
    const accumulatingModels = [
      { model: "AnalysisResult", containsPii: true, piiFields: ["ip"] },
      { model: "EmailCapture", containsPii: true, piiFields: ["email"] },
      { model: "OtpToken", containsPii: true, piiFields: ["email", "token"] },
      { model: "PostHogConfig", containsPii: false, piiFields: [] },
    ];
    const piiModels = accumulatingModels.filter((m) => m.containsPii);
    expect(piiModels).toHaveLength(3);
    // All three PII-containing models have no retention policy
    piiModels.forEach((m) => {
      expect(m.piiFields.length).toBeGreaterThan(0);
    });
  });

  it("Prisma schema contains all four accumulating models (confirms scope of gap)", () => {
    const schema = fs.readFileSync(PRISMA_SCHEMA, "utf-8");
    expect(schema).toContain("model AnalysisResult");
    expect(schema).toContain("model EmailCapture");
    expect(schema).toContain("model OtpToken");
    expect(schema).toContain("model PostHogConfig");
  });
});
